model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: seg_mask
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.058
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 640
        use_checkpoint: true
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: val/rec_loss
        ckpt_path: pretrained/256_vae.ckpt
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.SegMaskEncoder
      params:
        seg_mask_encoder_config:
          target: ldm.modules.encoders.modules.PassSegMaskEncoder
          params: {}
        mask_embed_dim: 1024
        context_dim: 640


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.celebahq.CelebAConditionalDataset
      params:
        phase: train
        im_preprocessor_config:
          target: ldm.data.celebahq.DalleTransformerPreprocessor
          params:
            size: 256
            phase: train
        test_dataset_size: 3000
        conditions:
          - 'seg_mask'
        image_folder: 'datasets/image_256_downsampled_from_hq_1024'
    validation:
      target: ldm.data.celebahq.CelebAConditionalDataset
      params:
        phase: test
        im_preprocessor_config:
          target: ldm.data.celebahq.DalleTransformerPreprocessor
          params:
            size: 256
            phase: val
        test_dataset_size: 3000
        conditions:
          - 'seg_mask'
        image_folder: 'datasets/image_256_downsampled_from_hq_1024'

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True